# [START app_yaml]
runtime: nodejs
env: flex

# [START env]
env_variables:
  SQL_USER: app_usr
  SQL_PASSWORD: app_user
  SQL_DATABASE: apigee_demo
  # e.g. my-awesome-project:us-central1:my-cloud-sql-instance
  INSTANCE_CONNECTION_NAME: apigeedemo-ritwik:us-west1:apigee-demo-1
# [END env]

# [START cloudsql_settings]
beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: apigeedemo-ritwik:us-west1:apigee-demo-1
# [END cloudsql_settings]
# [END app_yaml]
